# -*- coding: utf-8 -*-
"""Train delay problem ONIA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nxWFN0KL25GQtdUjgWrMbhY9_hM6lN-

**Train delay problem ONIA**

Este o problema de regresie. "You need to train a model capable of predicting delay_minutes based on the other features."

Trebuie sa trimiti un csv file with the following format:
SampleID,delay_minutes
0,12
1,3
2,2

Pasi de rezolvare problema:


1.   descarca si analizeaza fisierul de date
2.   transforma datele de tip string in date de tip numeric (int, float etc)
3.   feature engineering - elimina pentru model trasaturile irelevante
4.   selecteaza un model si implementeaza-l mai intai pe fisierul de antrenament
5.   separa fisierul de antrenament in 80/20 si testeaza modelul
6.   verifica eficienta modelului si reprezinta grafic
7.   aplica modelul pe setul de test
8.   genereaza documentul csv raspuns si descarca codul - incarca le pe platforma
9.   verifica scorul - daca nu este 100, revino pentru a imbunatati codul
"""

import numpy as np
import pandas as pd

train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")

train.head(5)

test.head(5)
test.info()

features = ["departure_time","distance_km","avg_speed_kmh","num_stops","weather","weekday","ticket_price","delay_minutes"]

train = train[features]

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

weather_mapping = {
    "sunny": 0,
    "cloudy": 1,
    "rain": 2,
    "fog": 3,
    "snow": 4
}

train["weather"] = train["weather"].map(weather_mapping).fillna(0)

train.head(5)

train["departure_time"] = pd.to_datetime(train["departure_time"])
test["departure_time"] = pd.to_datetime(test["departure_time"])

# Extragem minutele din zi
train["departure_minutes"] = train["departure_time"].dt.hour * 60 + train["departure_time"].dt.minute
test["departure_minutes"] = test["departure_time"].dt.hour * 60 + test["departure_time"].dt.minute
train.drop(columns = ["departure_time"], errors = 'ignore')

train.head(5)

label_cols = ["weekday"]  # aici pui ce este TEXT

encoder = LabelEncoder()

for col in label_cols:
    # concatenăm train + test pentru a avea aceleași etichete
    all_values = list(train[col].values) + list(test[col].values)
    encoder.fit(all_values)

    train[col] = encoder.transform(train[col])
    test[col] = encoder.transform(test[col])

X = train.drop(columns=['delay_minutes'])
y = train['delay_minutes']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    random_state=42,
    test_size=0.25
)

train.head(5)

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

rf = RandomForestRegressor(
    n_estimators=1200,
    max_depth=16,
    min_samples_leaf=2,
    min_samples_split=5,
    max_features='sqrt',
    bootstrap=True,
    random_state=42
)

X_train,X_test,y_train,y_test = train_test_split(X,y ,random_state=42,test_size=0.25, shuffle=True)

X_train = X_train.drop(columns=['departure_time'])
X_test = X_test.drop(columns=['departure_time'])
rf.fit(X_train, y_train)

from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'n_estimators': [200, 400, 600, 800,1200,1500],
    'max_depth': [10, 20, 30, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', None]
}

search = RandomizedSearchCV(
    rf,
    param_grid,
    n_iter=10,
    scoring='neg_mean_absolute_error',
    cv=5,
    n_jobs=-1,
    random_state=42
)

search.fit(X_train, y_train)
best_model = search.best_estimator_

print("Best params:", search.best_params_)
print("Best MAE:", -search.best_score_)
from sklearn.metrics import mean_absolute_error

predictions = rf.predict(X_test)

# f1_score is a classification metric, not suitable for continuous targets
# f1 = f1_score(y_test, predictions)
# print(f'Mean Squared Error: {f1}')

r2 = r2_score(y_test, predictions)
print(f'R-squared: {r2}')
mae = mean_absolute_error(y_test,predictions)
print(f'MAE equal to: {mae}')

test.head(5)

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, predictions)
print(f'Mean absolute error: {mae}')

test.head(3)

features_test = ["distance_km","avg_speed_kmh","num_stops","weather","weekday","ticket_price","departure_minutes"]

test = test[features_test]

weather_mapping = {
    "sunny": 0,
    "cloudy": 1,
    "rain": 2,
    "fog": 3,
    "snow": 4
}

test["weather"] = test["weather"].map(weather_mapping).fillna(0)

test.head(3)

X_t = test

delay_min_pred_test = rf.predict(X_t)

test_df = pd.read_csv('/content/test.csv')
SampleID = test_df['SampleID']

submission = pd.DataFrame({
    "SampleID": SampleID,
    "delay_minutes": delay_min_pred_test
})

print(submission)

submission.to_csv("submission.csv", index=False)