# -*- coding: utf-8 -*-
"""bac_sub_lupa_mar26_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIF5YEa2B6Ym23_RomcDRENkyrOvStVs
"""

import numpy as np
import pandas as pd

train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')

test.head(5)

s1_answer = test[test['liceu'] == 'COLEGIUL NATIONAL "UNIREA" FOCSANI'].groupby('preferinta_materie').value_counts()
print(s1_answer)
answer_s1 = 'MATEMATICA MATE-INFO'

s2_answer = train[(train['liceu'] == 'COLEGIUL NATIONAL "UNIREA" FOCSANI') & (train['materie'] == 'INFORMATICA MI C-C++')].groupby('preferinta_materie').value_counts()
answer_s2 = 2022
print(s2_answer)

!pip install catboost

#subtask 3

from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from catboost import CatBoostRegressor

cat_cols = ['materie','liceu','judet']
num_cols = ['procent_reusita','numar_candidati','preferinta_materie']
X = train[cat_cols + num_cols]
y1 = train['medie']
y2 = train['anomalie']
X_test = test[cat_cols + num_cols]

X_tr,X_val,y_tr,y_val = train_test_split(X,y1,test_size=0.2,random_state=42)
ctbr = CatBoostRegressor(
    learning_rate=0.03,
    max_depth=12,
    n_estimators=1000,
    cat_features=cat_cols

)

ctbr.fit(X_tr,y_tr)
y_pred = ctbr.predict(X_val)
print(f'The MAE for catboost is {mean_absolute_error(y_val,y_pred)}')

ctbr.fit(X,y1)
test_pred1 = ctbr.predict(X_test)

from catboost import CatBoostClassifier
from sklearn.metrics import roc_auc_score
from sklearn.metrics import auc
X_tr2,X_val2,y_tr2,y_val2 = train_test_split(X,y2,test_size=0.2,random_state=42)
ctbc = CatBoostClassifier(
    learning_rate=0.03,
    max_depth=6,
    n_estimators=1000,
    cat_features=cat_cols

)

ctbc.fit(X_tr2,y_tr2)
y_pred2 = ctbc.predict(X_val2)
print(f'The roc_auc_score for catboost is {roc_auc_score(y_val2,y_pred2)}')

ctbc.fit(X,y2)
test_pred2 = ctbc.predict(X_test)

submission = pd.DataFrame({
    'id': np.concatenate([
        [1],
        [2],
        test['id'],
        test['id']
    ]),
    'subtaskID': np.concatenate([
        [1],
        [2],
        [3] * len(test),
        [4] * len(test)
    ]),
    'answer': np.concatenate([
        [answer_s1],
        [answer_s2],
        test_pred1,
        test_pred2
    ])
})

submission.to_csv('submission_4_mar13th.csv')